termination/termination.go
As a result of [this](https://blog.gruntwork.io/delaying-shutdown-to-wait-for-pod-deletion-propagation-445f779a8304) limitation in K8s we want to wait before termination
so that things can shutdown cleanly and remove themselves.
=> Add termination delay to termination Handler for K8s

testing/compiler/compiler.go, testing/compiler/compiler_test.go, testing/compiler/internal/cmd/main.go, testing/compiler/internal/cmd/main_test.go, testing/compiler/testdata/coverage.txt
We use this in a few places now, and I cleaned it up a bit for the latest service, so figured it was useful here.
=> Add compiler package

testing/download/downloader.go, testing/download/downloader_test.go
Allows clients to easily remove files that they don't want to be cached.
I preferred this to changing the Download method signature.
=> Remove previously cached downloaded files

testing/releases/releases.go, testing/releases/releases_test.go
can remove this once merged....
https://github.com/circleci/output/pull/42/files#diff-654d0f35a02225fae4fd71218d23ba0dc48939ab2cf3dc25c4443a414e695b6bR251
=> Tolerate differences in checksum file

o11y/honeycomb/honeycomb.go
would like to 'canary' this first somehow
shame there is not the top level func on beeline - so had to copy and paste this :|
=> Default to async child spans

httpclient/httpclient.go, httpclient/httpclient_test.go
Even if we do not care about a response the client must read all of
the response body and close it to be able to reuse the connection.
It is possible that a response decoder does not read the full body
(though it appears the JSON decoders we use do)
=> Make sure we can use keep alives.

httpclient/httpclient.go, httpclient/httpclient_test.go
The metrics that demonstrated that we were not using many persistent connections improved with the previous body read and close PR, but not enough - it was clear that we were not pooling enough connections...
You can see the improvement above but still a low number of active server connections - and a steady growth in new connections.
Previously we were using the default MaxIdleConnectionsPerHost (2)
so we were closing and creating many more connections than we need to.
This uses the previous configuration value to set the max idle connections
resulting in that many 'pooled' connections.
This commit also adds more godocs to the httpclient.
=> Add a sensible connection pool

worker/worker.go, worker/worker_test.go
- We're finding we want this a lot in some projects.
- Rename worker test functions to follow Go naming conventions.
- Move all error handling to the defer block, and use a `switch` to make it clearer.
=> Allow `worker` to backoff on any error if desired

db/transactions.go
As a follow up to retrying the transaction when an individual statement fails due to a bad connection.
We also need to trap for a bad connection on the commit.
For info here is a trace of a good transaction retry...
https://ui.honeycomb.io/circleci/datasets/execution/result/kiV3CMjV5rz/trace/5MRyc1xfMYx
=> Trap bad connections on the transaction commit [CIRCLE-37662]

db/transactions.go, db/transactions_test.go
We can see that during context deadline errors the commit
is attempted and fails since the driver has already rolled
back.
Instead of only specifically handling the context cancel
handle both kinds of context error.
=> Handle both context errors

httpclient/httpclient.go
JIRA: [CIRCLE-33831]
- For most http requests that succeeds within 1 try, this should cut
down the amount of spans in half. For retries, we lose out on the
logical grouping of spans, but all the tries are still there, so it
shouldn't be the end of the world.
[CIRCLE-33831]: https://circleci.atlassian.net/browse/CIRCLE-33831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CIRCLE-33831] Remove the parent span for http requests

go.mod, go.sum, testing/rabbitfixture/internal/rabbit/client.go, testing/rabbitfixture/rabbitfixture.go
https://github.com/michaelklishin/rabbit-hole/issues/219
=> `testing/rabbitfixture`: Remove dependency on `rabbit-hole`

testing/httprecorder/ginrecorder/middleware.go, testing/httprecorder/ginrecorder/middleware_test.go, testing/httprecorder/httpnetrecorder/middleware.go, testing/httprecorder/httpnetrecorder/middleware_test.go
- For `gin` and plain `http.Net`
=> `testing/httprecorder`: Add recording middlewares

.github/dependabot.yml
- This is used in a bunch of places, so lets upgrade all the dependencies all together.
=> Switch to daily updates

httpclient/httpclient.go, httpclient/httpclient_test.go, testing/releases/releases.go
- Allow setting additional headers on http client
- Make the httpclient request a fluent API
=> Allow setting user-agent on the httpclient

httpclient/httpclient.go, httpclient/httpclient_test.go
- `httpclient` Allow setting raw body
=> [TASKS-903]       `httpclient` Allow setting raw body

README.md, go.mod, go.sum, httpclient/dnscache/dnscache.go, httpclient/dnscache/dnscache_test.go, httpclient/dnscache/net.go, httpclient/dnscache/net_test.go, httpclient/httpclient.go, httpclient/httpclient_test.go
- Add a simple DNS caching package.
=> `httpclient/dnscache`: New package

db/transactions.go
- We're heavily sampling this span anyway, and the sampling messes up the trace view when this span is sampled out.
=> `db`: Remove transaction span

httpclient/example_httpclient_test.go
To add an example about RouteParams
=> Add an example usage of RouteParams

httpclient/httpclient.go
N.B. - don't merge until we have tried this in a few repos...
To improve the flexibility by injecting different roundtrippers
this change the config to accept Roundtripper instead of *Transport.
We expose the ability to modify the transport if it is
http.Transport so this should not make transport alterations any more
annoying.
=> Add the ability to override the transport [DONT MERGE]

datadog/client_test.go, db/integration/db_test.go, db/transactions_test.go, grpc/proxy_test.go, httpclient/httpclient_internal_test.go, httpclient/httpclient_test.go, httpclient/metrics/metrics_test.go, httpserver/client_cancel_test.go, httpserver/tracking_test.go, mongoex/mongo_test.go, redis/redis_test.go, releases/release/handler_test.go, releases/release/list_test.go, testing/dbfixture/dbfixture.go, testing/download/downloader_test.go, testing/miniofixture/miniofixture.go, testing/releases/latest.go, testing/releases/latest_test.go, testing/runner/runner_test.go, testing/testrand/hex_test.go
WE see this code repeated in a lot of acceptance and integration tests
=> Add a test download helper to get latest

.circleci/config.yml, .golangci.yml, db/transactions.go, do, grpc/proxy.go, httpclient/httpclient.go, httpclient/metrics/metrics.go, o11y/wrappers/o11ygin/o11ygin.go, testing/download/downloader.go
- Also upgrade required go tools
=> `ci`: Add Go 1.19 to matrix

o11y/o11y.go, testing/fakemetrics/fakemetrics.go
https://docs.datadoghq.com/metrics/types/?tab=histogram#metric-types
=> Add support for Datadog histogram

o11y/wrappers/o11ygin/o11ygin.go, o11y/wrappers/o11ygin/o11ygin_test.go
This particular panic is thrown for normal disconnects. Just add the error to the span, rather than reporting to rollbar
=> Don't rollbar for aborts

releases/release/list.go, releases/release/list_test.go
Example of where this gets used:
https://github.com/circleci/docker-provisioner/blob/21e127f2ffb4a848d1b1316b568804123ab3317a/api/externalapi/download_test.go#L70-L74
=> Add QueryParams helper to Requirements in releases

grpc/dial.go
The o11y added will allow viewing all outgoing GRPC calls within
a service on honeycomb. It does not create new spans so there should be
no additional costs.
There is a pre-existing test covering this code path.
=> [TASKS-1290] Add o11y to GRPC calls

httpclient/httpclient.go, httpclient/httpclient_test.go
Adds an opt-in to disable the existing backoff behaviour when receiving a `429` from the server.
=> EXEC-2603 - Allow disabling rate limit backoff

go.mod, go.sum, redis/cluster.go, redis/health.go, redis/metrics.go, redis/redis.go, redis/redis_test.go, redis/system.go, testing/redisfixture/redisfixture.go
In preparation to start using redis v7 cluster-mode.
=> Update go-redis/redis/v8 to redis/go-redis/v9

plugin/releaser/internal/cmd/main.go, plugin/releaser/releaser.go, plugin/releaser/releaser_test.go
Bundles the `Compiler` and `Releaser` with some plugin specific elements to provide a standardised mechanism for plugin authors to build and upload plugins.
=> Add Plugin Releaser Utility

o11y/wrappers/o11ygin/o11ygin.go, o11y/wrappers/o11ygin/o11ygin_test.go
This does not explicitly change functionality, rather asserts on existing functionality.
There is a field added to track the occurrences of internal gin errors (which we have seen on render as the underlying connection disappears from the response writer)
Adds a code comment to explain the ClientCancelled middleware behaviour more clearly.
=> Clarify how ClientCancelled works and report on render errors

.circleci/config.yml, docker-compose.yml, testing/redisfixture/redisfixture.go
- Also make sure it's never zero
=> `testing/redisfixture`: Add randomness to Redis fixture DB number

releases/download/downloader.go, releases/download/downloader_test.go
=> Revert "Move from http.Client to httpclient.Client for retry goodies"

releases/release/list.go, releases/release/list_test.go
Allow "server" releases to be validated
=> Enable server versions in release

o11y/otel/otel.go, o11y/otel/otel_test.go
I wrote this without help from anyone, don't look at the commit history, thanks.
=> Tests for honeycomb dataset as a resource attribute

httpclient/httpclient_test.go, o11y/honeycomb/honeycomb.go, releases/download/downloader_test.go
Any otel tooled up services should line up with beeline tooled up clients
=> Emit w3c trace propagation headers

config/o11y/o11y.go, o11y/otel/otel.go, o11y/otel/otel_test.go, o11y/otel/sampler.go
So we can keep similar client side sampling as we cut over to Otel
=> Add a hc compatible client side sampler for Otel

o11y/otel/otel.go, o11y/otel/otel_test.go
fix AddGlobalField and add a couple of service fields
=> Small fixup to global o11y fields

o11y/otel/otel.go, o11y/otel/otel_test.go, o11y/otel/sampler.go
So we can sample out individual spans, based on their attributes once they are ended
=> Add span based tail sampling [FND-26]

o11y/otel/otel_test.go, o11y/otel/sampler.go
Slight bug meaning sampling on the span names was not working
=> Actually make the span name available to the sampler [FND-26]

o11y/otel/otel.go, o11y/otel/otel_test.go
this tests for and fixes the source of two critical issues
=> Fixup possible panics and fatals

o11y/otel/metrics.go, o11y/otel/otel.go, o11y/otel/otel_test.go
hc doesn't even add the field....
=> Don't count nil errors as failures

httpserver/ginrouter/default_test.go, testing/testcontext/context.go
Hopefully to flush out sharp corners of otel
=> Testcontext uses otel [FND-26]

do, testing/redisfixture/redisfixture.go
Porting circleci/backplane-go#353
=> Don't allow test skipping in CI

testing/redisfixture/redisfixture.go
See: https://github.com/circleci/ex/pull/945#discussion_r1682403677
=> Fix error check in Redis tests

httpclient/httpclient.go, httpclient/httpclient_test.go
This will allow individual requests to set an overall timeout including retries.
This might be of use where some calls are more important than others or where blocking for overly long on some requests might be more problematic than others
=> Add a per request maxElapsedTime to httpclient

config/o11y/otel.go, o11y/honeycomb/honeycomb.go, o11y/o11y.go, o11y/otel/helpers.go, o11y/otel/otel.go, o11y/otel/otel_test.go, testing/jaeger/client.go
This is the first introduction of the concept of a golden trace.
This is an addition to the API, and may be subject to change, as we observe how it behaves.
=> Introduce golden trace concept [FND-44]

httpclient/metrics/metrics.go
Based on [this panic](https://kibana.tools.circleci.com/_plugin/kibana/app/discover#/doc/18f613c0-f43b-11eb-bbbf-6b3b9eb8ab1a/nomad_906?id=a482846d-9ba9-11ef-9902-1e909ef53f10) in build-agent outer, it seems like it's possible for gotConn's tracing to be invoked before getConn has completed. The ex client tracing is explicitly configured to panic in the case that gotConn is invoked with a nil `con` - which I believe is due to this race.
=> [ONCALL] Lock request mutex on GetConn invocation

o11y/honeycomb/honeycomb.go, o11y/o11y.go, o11y/otel/otel.go, o11y/otel/otel_test.go
=> Cut down the golden span API

releases/download/downloader.go, releases/download/downloader_test.go
Adds additional retry mechanisms around the HTTP call in the `downloader` to better handle an edge case where the HTTP client's context times out during the decoding of the response body.
=> More resilient downloader retrying

o11y/httpmetrics/provider.go
The mutex was only guarding one method, so a sync once i think is the better option.
=> use once to guard closing the channel

o11y/otel/attribute.go, o11y/otel/attribute_test.go
https://ui.honeycomb.io/circleci/datasets/execution/board-query/BeAvwiwA3Lc/result/eHFgaVbYGYU
Distributor time in queue on the span is zero currently :(
=> Improve otel attribute mapping
