circleci/ex

- config/env/env.go
- config/env/env_test.go
Adds a function with tests to env package that will inspect an env and will parse the value as a time.Duration if present.
I added this to ex as I needed to do for the output services, but I thought it could be used in other places, and adding the parse errors to the overall loader errors seems a bit cleaner, as well.
> [CIRCLE-35532] Add function to config to parse duration envs

- datadog/client.go
- datadog/client_test.go
Have extracted this out of old code from nomad-scaler used to pull metrics from Datadog. This will be used to compare info with Nomad and Docker versions for SLOs around time since latest upgrade.
> Add datadog client library

- httpclient/httpclient_test.go
- httpserver/httpserver.go
Since we often see handlers setting timeouts of 5s or more on the
ongoing it makes sense to increase the server shutdown timeout, which
increases the chance that we have a clean shutdown.
The server shutdown error is wrapped to make it more clear where the
error is coming from.
This also decreases the chance of seeing a recent test flake where
the server shutdown was occasionally timing out.
Since concurrency is not parallelism we sometimes see less parallelism
in the test runs that causes us to use fewer concurrent connections.
The test has been changed to increase the likelihood of seeing the
expected concurrency, and is also more tolerant to variations.
The interplay between the deferred test context cancellation and the
t.Cleanup is a bit confusing, which happens first? moving the …
> Fix the flaky pool test

- README.md
- config/o11y/o11y.go
- o11y/honeycomb/honeycomb.go
- o11y/honeycomb/honeycomb_test.go
- o11y/o11y.go
- system/metrics.go
- system/system_test.go
- testing/fakemetrics/fakemetrics.go
- Also use the direct metrics interface for the system metrics, instead of creating spans.
> Expose `MetricsProvider` from o11y `Provider`

- testing/compiler/compiler.go
`Compiler.Compile()` was calling `filepath.Dir()` on the GOROOT which drops the last item in a path string and so was creating an invalid path on linux systems. I believe this bug wasn't being caught on mac systems due to a quirk in how mac installs Go (I think the GOROOT points to a symlink folder nested in the actual go directory), but the change should still work on mac regardless.
> Fixed compiler clobbering GOPATH in linux

- testing/testcontext/context.go
- testing/testcontext/context_test.go
- This means that code can send metrics under test without needing `nil` checks.
> Add No-op metrics provider to `testcontext.Background()`

- db/transactions.go
Since transactions need to use a single connection and can execute
multiple statements they all have to use the same connection.
If that connection goes bad - there is no point retrying the individual
statements - since they still need the transaction which is now associated
with a bad connection.
Begin and End transaction are application side calls so there is no stdlib
retry mechanism like there is on direct DB statements.
The ex library is robust wrt rollbacks in a failed transaction, so we can
be reassured that retrying a transaction is safe.
This change adds a minimal number of retries (similar to the stdlib count)
in the face of a bad connection.
Exactly what causes a bad connection is unclear. Some sources suggest it can
be a side effect of the server timing out a transaction. We …
> Retry our transactions on bad connections

- redis/redis.go
- redis/redis_test.go
This adds the ability to choose which Redis DB on the instance to use when creating the client.
> Make Redis DB configurable

- o11y/honeycomb/honeycomb.go
- It's wasteful to send spans to both stdout and our trace provider, if we only look at the trace provider.
> `o11y`: Add `none` output mode

- .circleci/config.yml
- docker-compose.yml
- go.mod
- go.sum
- testing/redisfixture/redisfixture.go
- testing/redisfixture/redisfixture_test.go
- The previous strategy of deriving the package name wasn't always working.
- If you put the call to redisfixture in a shared test helper, then the same package name was always dervied.
- Now we just enforce a really big space for the DBs (1 million), so there's much less chance of collision.
> `redisfixture`: Use an enforced bigger hash space

- httpclient/doc.go
- httpclient/httpclient.go
- httpclient/httpclient_test.go
This grew into a few separate cleanups. Whilst fairly self contained I am Happy to split into separate PR's for the reviewers pleasure.
During the retry loop any of the retryable http errors are treated as
warnings. Only once the retrying is over do we then treat the
HTTPError as an error, because then it is fair that the client
errored. Whilst we don't have the higher level call span anymore (for
cost savings) but this is actually a reasonably sensible default
since it is up to the client code to decide how it manifests the
HTTPError.
During recent investigations it was clear the default .5s
before retrying the next request resulted in too few retries.
The initial retry period is reduced to 50ms resulting in 5-6
retries in our more common 3s total timeout calls, from a
previous 2-3. …
> Retry and o11y improvements.

- config/o11y/o11y.go
- config/o11y/o11y_test.go
- o11y/honeycomb/honeycomb.go
- o11y/o11y.go
- testing/fakemetrics/fakemetrics.go
- testing/fakestatsd/fakestatsd.go
- Avoid the associated costs of Datadog telemetry for agents where we're not interested in it.
- Add a recording statsd server for testing the statsd integation.
- Also close the statsd client on o11y close.
> Allow disabling statsd telemetry

- db/error.go
- db/integration/db_test.go
Changing errors has the potential to be a breaking change, however this only changes the err.Error() value.
That can be a breaking change - though it should not be, (folk *should* not test the string (though with bad API's they may have to)). 
Tests are likely the most common way the Error() is tested, though here we are only adding to the message, so hopefully there are not too many tests checking the whole Error() string in packages that use `ex\db`
> Include more pq error detail

- testing/dbfixture/dbfixture.go
- testing/fakestatsd/fakestatsd.go
- testing/rabbitfixture/rabbitfixture.go
- testing/redisfixture/redisfixture.go
- testing/types/doc.go
- testing/types/types.go
Use `TestingTB` interface instead of `testing.TB`
`TestingTB` allows for non `*testing.T` instances to be passed in. This allows the testing utils to work with other test runners like Ginkgo.
> Use TestingTB interface instead of testing.TB

- recontext/context.go
- recontext/context_test.go
Enforces a new mandatory timeout/deadline to prevent stuck contexts.
Supersedes https://github.com/circleci/ex/pull/147
> recontext lib for deriving contexts that outlive parents

- testing/runner/internal/testservice/main.go
- testing/runner/runner.go
- testing/runner/runner_test.go
Which means that we need to be able to allow for services which
dont have an API
Add a new Ready method to expose the readiness internals so callers
can control the timeout and when the serverName is empty then dont
test for the server port, to handle non api services.
> Be more explicit about port detection failure.

- system/metrics.go
- system/system_test.go
To use tags, the MetricProducer will also need to implement the
tagProducer interface. This was implemented as an additional interface
to maintain compatibility with library consumers.
> Support tags in MetricProducer gauge metrics

- mongoex/mongo.go
- mongoex/system.go
- mongoex/system_test.go
- We don't want to limit what users can configure / use the mongo driver for.
- Also take a full mongo client options struct (though we always override the URL / client name).
> `mongoex`: Give back a Mongo client, rather than a database

- system/system.go
- system/system_test.go
- I have tried this change out with a few services, and it produced the desired result.
> `system`: Run cleanups in reverse

- httpclient/httpclient.go
- o11y/wrappers/o11ygin/o11ygin.go
- o11y/wrappers/o11ygin/o11ygin_test.go
- o11y/wrappers/o11ynethttp/o11ynethttp.go
- o11y/wrappers/o11ynethttp/o11ynethttp_test.go
- testing/fakemetrics/fakemetrics.go
- This means that if the spans get sampled, we still get metrics
> Emit o11y middleware metrics using MetricsProvider interface

- system/gauges.go
The metrics provider interface uses float64, so using float64 for
TaggedValue reduces unnecessary type casting.
> Use float64 for TaggedValue instead of float32

- httpclient/httpclient.go
Otherwise the default value of `Go-http-client/1.1` is lost.
> `httpclient`: Only set UserAgent additional header if it has a value

- httpclient/httpclient.go
- httpclient/httpclient_internal_test.go
- httpclient/httpclient_test.go
- httpclient/metrics/metrics_test.go
- httpserver/ginrouter/default_test.go
- o11y/wrappers/o11ygin/o11ygin_test.go
- o11y/wrappers/o11ynethttp/o11ynethttp_test.go
- testing/rabbitfixture/internal/rabbit/client.go
- testing/releases/releases.go
- testing/runner/runner_test.go
- NewRequest now returns a reference, so the request can be mutated and
behave as expected
- The request struct is un-exported, forcing the use of NewRequest
> `httpclient`: Use functional options for request construction

- config/o11y/o11y.go
- o11y/honeycomb/honeycomb.go
- o11y/honeycomb/honeycomb_test.go
- Key is technically not needed as we have a custom client, but it
supresses the warning from beeline-go
> Wire in honeycomb key and service name

- config/o11y/o11y.go
An optional feature that will enable users to leverage Refinery. The change is backward compatible as current library users will be using an empty string that defaults to Honeycomb Public API.
We are already allowing custom Honeycomb Hosts for internal testing. Now we will expose this option to end-users.
> SRENG-358: Allow Custom Honeycomb Host for Refinery

- testing/testrand/hex.go
- testing/testrand/hex_test.go
This is only a small helper, but is copied around a lot.
> Add a testrand.Hex(n) test helper for generating random hex strings

- go.mod
- go.sum
- grpc/config.go
- grpc/dial.go
- grpc/proxy.go
- grpc/proxy_test.go
We are seeing the gRPC bug (as mentioned in the comments) in any of our grpc clients when running in an environment with a proxy
> Add grpc helpers for better behaviour and to avoid proxy bugs

- go.mod
- httpclient/httpclient.go
- httpclient/httpclient_test.go
- httpclient/proxy_test.go
If we want to change one thing on the transport, we currently have
to repeat all the connection options, this allows us to provide a
way to override transport options after the standard setup.
I added this primarily to explicitly disable clients honouring proxies - we could add that as a specific config option
but this felt a bit more flexible.
> Add a transport mutating config option.

- worker/worker.go
This moves the `app.loop_name` field from the first span in the trace to the root span (which results in the field being available on all spans in the trace)
The name of the field doesn't change so this isn't a breaking change.
This allows us to more easily add sampling to worker loops.
For example:
```golang
SampleTraces: true,
SampleKeyFunc: func(fields map[string]interface{}) string {
return fmt.Sprintf("%s %s",
fields["app.loop_name"],
fields["result"],
)
},
SampleRates: map[string]int{
"myLoop success": 1e3,
},
```
Previously the above sampling would only filter out the initial span since it was the only one to have the `app.loop_name`, all other spans in the trace would still be kept.
Now since the field does exist on all spans the sampling works for the whole worker loop. (What …
> Add worker loop name to root span

- httpclient/httpclient.go
- httpclient/httpclient_test.go
There is a strange situation where the connection used in a request that timed out
is kept active in the pool and reused, timing out again.
This attempts to catch some of those cases and force the connection to close.
> Attempt to force a bad connection to be closed.

- go.mod
- go.sum
- httpclient/httpclient.go
- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
- o11y/o11y.go
- o11y/wrappers/o11ygin/o11ygin.go
- o11y/wrappers/o11ynethttp/o11ynethttp.go
Introduce the construction of helpers, for some stuff that is not part of the main o11y provider interface 
two helpers for http propagation
one helper for improved more generic testability
> Abstract o11y http propagation

- catalog-info.yaml
This adds the Backstage YAML file to ex, so it can be discovered and added to the catalog. This will help increase discoverability and allow us to refer to it as a dependency in other projects.
> Add Backstage catalog file

- o11y/honeycomb/honeycomb.go
- o11y/wrappers/o11ygin/o11ygin_test.go
- o11y/wrappers/o11ynethttp/o11ynethttp_test.go
- system/system_test.go
This insects a span for the warning and error fields and produces a count metric tagged with the span name - which is relatively low cardinality, but adds enough context that the dashboards can help us zoom inot the problem
We use field names with an _error suffix to indicate a problem span but only in a path that can still make progress, e.g. a fail open path.
Since the field names are varied it is hard to add monitors, so this detects those fields, adds a standard 'failure' field to the span with the prefix part as the value and also produces a failure metric and uses the prefix part as a tag.
> 💛 Add standard metrics for warning and error [TASKS-1158]

- go.mod
- go.sum
- releases/release/list.go
- We already use the tinylru library elsewhere, no need to have two separate cache libraries.
- Hashicorp's library just broke its API, so this is a good time to switch over.
> Remove dependency on hashicorp cache

- testing/releases/latest.go
- testing/releases/latest_test.go
Without this we ends up creating cache folders like:
`base/which/which/version-1.1/os/arch/`
which should be:
`base/which/version-1.1/os/arch/`
> Remove the double path from testing releases DownloadLatest

- releases/download/downloader.go
- releases/download/downloader_test.go
Leverage the `httpclient.Client` to allow for automatic retries within the timeout window
> Move from http.Client to httpclient.Client for retry goodies

- releases/download/downloader.go
- releases/download/downloader_test.go
It seems the build-agent e2e tests often tripped the default 5 second request + decode timeout when grabbing the output binaries to setup the harnesses. 
This PR re-introduces the adoption of `httpclient.Client` in the ex downloader, and also adds a 30 second per-request timeout to avoid using the lower default value. This was tested by pinning ex to a commit-hash version from this branch [here](https://app.circleci.com/pipelines/github/circleci/build-agent/13302/workflows/6d91b455-1139-4780-a701-65708da7964e).
> [EXEC-3010] http.Client -> httpclient.Client for release downloader (again)

- rabbit/publisherpool.go
- rabbit/publisherpool_test.go
This should allow messages to be posted even though no exchanges exist. Optional messages allow us to start emitting messages even though nobody listens for them yet, which allows people to start working with the new messages before we make them mandatory.
Definitely the "mandatory" should happen afterwards, but for now it allows us to be less dependant on when a team is ready to start listening for messages before we deliver those.
> [EXEC-3120] Allow non-mandatory messages to be published

- o11y/o11y.go
The documentation for FromContext mistakenly used to say that it returns nil if the provider isn't found in the context, where in fact it returns a no-op provider instead.
> Correct documentation

- go.mod
- o11y/otel/config.go
- o11y/otel/otel.go
- o11y/otel/otel_test.go
Sets the custom header that the collectors use to direct to the correct dataset (this fooked us up in the past)
Adds a otel gRPC server to assert that the header is received.
> Otel - set the honeycomb dataset in the grpc headers

- o11y/otel/otel.go
- o11y/otel/otel_test.go
After a successful programmatic verification from the company Slack.
> Move the `x-honeycomb-dataset` attribute to the tracer provider

- o11y/wrappers/o11ygin/o11ygin.go
- o11y/wrappers/o11ygin/o11ygin_test.go
This header can then be inspected by the API gateway and added to telemetry for better segmentation.
> Add the X-Route header

- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
- o11y/o11y.go
- o11y/otel/helpers.go
- o11y/otel/otel.go
- o11y/wrappers/o11ynethttp/o11ynethttp.go
As flushed out by testing on a crashing feature-flags !
GetSpan returns nil if there is not span in the current context, and otel propagation was not injecting it.
> Makes sure a propagated otel span is added to the context

- o11y/otel/helpers.go
- o11y/otel/otel_test.go
The previous incantation was overly like how hc does it and not needed and resulted in a nonRecordingSpan!
> More hacking on fixing the propagation

- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
This looks to be causing lots of 'late' sampled in events from refinery
> Disable w3c propagation [FND-26]

- httpclient/httpclient.go
- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
- o11y/o11y.go
- o11y/otel/helpers.go
- o11y/otel/otel.go
The option is only settable on the http client since this appears to be causing all the propagation actoss dataset sampling problem.
> Add an option to disable w3c trace header propagation

- o11y/warning.go
- o11y/warning_test.go
We can probs use errors.Join instead of "github.com/hashicorp/go-multierror"
> Joined errors only report warning if all errors are warnings

- config/o11y/otel.go
- o11y/otel/otel.go
E.g when we tool up high throughput services for otel - i think we might overwhelm logging if we do text 
ex honeycomb - never logged spans - because we believed in tracing
the otel stuff started dumping to stdout - kind of in preparation for heavy server side sampling, but we do need to disable text logged spans
> Allow some services to disable text logging of spans.

- httpclient/httpclient.go
- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
- o11y/o11y.go
- o11y/otel/helpers.go
- o11y/otel/otel.go
- o11y/otel/otel_test.go
- testing/jaeger/client.go
Marking a span as flattened - will roll up any attributes into the parent span. each child from a flattened span will be considered flattened.
If the httpcl request is flattened then all server spans will be considered flattened, but they will not pas back the flattened fields to the client. Essentially this will cause ALL server side spans to be dropped.
> Add the option to flatten otel spans

- config/o11y/otel.go
- o11y/otel/otel.go
- testing/testcontext/context.go
- testing/testcontextotel/context.go
Currently, in tests we miss spans that haven't been batched processed. In some tests this means all of them.
Provide a test option and configure it in the testcontexts. This option switches to simple span processing which immediately exports spans on end. 
It also implements a basic otel log
> Use simple span processing in tests & otel logs

- rundef/maxprocs.go
The library returns an undo function, not the limit as the MEMLIMIT one does
> [EXEC-4719] Correct the limit output of max procs

- rundef/rundef.go
The errgroup was not needed here, I just intended to handle the errors together. Join is a better fit
> [EXEC-4719] Remove error group from rundef.Defaults as not needed

- o11y/otel/otel.go
- o11y/otel/otel_test.go
Without `WithEndpointURL` traces are always sent to `/v1/traces`
> Allow setting of otel path for proxying traces

- config/o11y/otel.go
- o11y/httpmetrics/provider.go
- o11y/httpmetrics/provider_test.go
- o11y/otel/otel.go
- o11y/otel/otel_test.go
This is not currently in use anywhere, so shouldn't cause any breakages
> Make the otel & http host names more consistent

- o11y/otel/otel.go
The WithEndpointURL option figures out if insecure is required automatically. It was never intended to be used here
> Remove insecure flag from otel exporter

- httpclient/httpclient.go
- httpclient/httpclient_test.go
- o11y/honeycomb/honeycomb.go
- o11y/httpmetrics/provider_test.go
- o11y/o11y.go
- o11y/otel/helpers.go
- o11y/otel/otel.go
- o11y/otel/otel_test.go
- o11y/spanopt.go
- o11y/wrappers/o11ygin/o11ygin.go
- rabbit/publisherpool.go
- rabbit/publisherpool_test.go
- rundef/automem_test.go
- rundef/rundef.go
The variadic options stle API is a bit verbose, but avoids a break to the API and is generally only going to be used in library code, so should have minimal impact on day to day use of spans.
(managed to drag in some linter fixups somehow)
> Start using formal otel span kind

- testing/cmpextra/or.go
Sometimes, your happy with a couple of different outcomes in a test. Here is a `cmp.Comparison` that accounts for that
> Add a cmp comparison for Or

- httpclient/httpclient.go
The amazon support folks need request IDs (they sent [this link](https://docs.aws.amazon.com/AmazonS3/latest/API/get-request-ids.html)) to continue their deep dive into failed downloads of the oidc plugin. 
This seems like the most straightforward way to get them correlated with a bad download.
> [EXEC-4742] Add aws request ID header values to the trace for debugging

- httpclient/metrics/metrics.go
We have noticed that task-agent is panicking occasionally due to this tracing logic, and a previous attempt to "solve" it with additional locking was unsuccessful. 
Since the root cause of this seemingly out of order trace hook invocation is not clear, I've opted here to choose to simply not panic and early-return when this situation arises. This causes us to lose some metrics for requests that run into this scenario.
> Remove panic when gotConn is invoked with a nil connection

- httpclient/httpclient_test.go
- o11y/o11y.go
> Don't include internal baggage as span attributes

- testing/releases/latest.go
- testing/releases/latest_test.go
- testing/releases/releases_test.go
Found a failed download of the E2E binary [here](https://app.circleci.com/pipelines/github/circleci/build-agent/33719/workflows/94bf3942-c6ac-4d0d-9ced-d0756d208d2c/jobs/259545/tests#failed-test-0), so I'm adding the ability to pass through an attempt timeout to the underlying downloader in the `releases.DownloadLatest` call.
> Allow providing an attempt timeout for latest release download

- httpclient/httpclient.go
- releases/release/handler.go
- releases/release/handler_test.go
This removes the dual-path code we had for allowing HTTP GET requests with bodies as well as parameters. Now we are behind WAF and RT-724 is complete we can remove the dual-path and streamline.
This fixes another issue where the release handler will return an error and the value, rather than returning during the error.
> Remove GET with Body support now RT-724 is complete

- o11y/httpmetrics/provider.go
- o11y/httpmetrics/provider_test.go
In an attempt to have the ex-o11y pathways behave more like the DD agent pathways
> Add timestamp to httpmetric

- httpclient/metrics/metrics.go
'host' is reserved and it clutters the host maps / host lists in DD (and it is possible we are charged for them as a host (tbc))
This will mes with a few dashboards - but should not be used in any alerts
I'll fixup where I find them in dashboards
> Rename the host tag from http metrics

- config/o11y/otel_test.go
- o11y/otel/otel_test.go
- o11y/otel/sampler.go
the config test change is incidental - i just noticed it was not testing otel setup :|
> make duration_ms available in samplekeyfunc for otel

- config/o11y/otel.go
- o11y/otel/otel_test.go
this resource attribute will be used to skip refinery in the otelcollector - pr upcoming
> Option to disable tail sampling

- o11y/o11y.go
- o11y/o11y_external_test.go
We pass propagation around via env vars across exec'ed processes in a few places hence adding to this common place
> To and from full propagation string

- o11y/o11y.go
- o11y/o11y_test.go
Function to set spans sampled in, during tail sampling. So they aren't filtered out.
> Add SetSpanSampledIn
